jdbc:
  url: jdbc:mysql://localhost:3306/student?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  username: root
  password: su201314
web:
  controller: site.arookieofc.controller
server:
  port: 8080